capstone_project/authentication/routes.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from capstone_project.models import User, db
from capstone_project.forms import UserLoginForm, UserSignUpForm, ChangePassword
from werkzeug.security import check_password_hash, generate_password_hash
from flask_login import login_user,logout_user, login_required
from flask_login import login_required, current_user



auth = Blueprint('auth', __name__, template_folder='auth_templates')

@auth.route('/signup', methods = ['GET','POST'])
def signup():
    form = UserSignUpForm()
    try:
        if request.method == "POST" and form.validate_on_submit():
            email = form.email.data
            first_name = form.first_name.data
            last_name = form.last_name.data
            password = form.password.data
            password1 = form.password1.data
            if password != password1:
                flash('Passwords do not match', 'error')
                return render_template('signup.html', form=form)
            user = User(email, password, first_name, last_name)
            
            db.session.add(user)
            db.session.commit()
            
            flash(f"You have successfully created a User account {email}", "user-created")
            
            return redirect(url_for('site.home'))
    except:
        raise Exception('Invalid From Data: Please Check Your Form')
            
    return render_template('signup.html', form=form)
            
            
    

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()
    try:
        if request.method == "POST" and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email, password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('You were successfully logged in via Email/Password', 'auth-success')
                return redirect(url_for('site.profile'))
    except:
        raise Exception("Invalid Form Data: Please check your form and try again")
    
    return render_template('signin.html', form=form)




@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('site.home'))



@auth.route('/passwords', methods = ['GET','POST'])
@login_required
def change_password():
    form = ChangePassword()
    # if request.method == 'POST':
    return render_template('changepass.html', form=form)


@auth.route('/password', methods = ['PUT','POST'])
@login_required
def change_pass():
    new_password = request.form['new_password']
    confirm_password = request.form['confirm_password']

    if new_password != confirm_password:
        flash('New passwords do not match')
        return redirect(url_for('auth.password'))

    current_user.password = generate_password_hash(new_password)
    db.session.commit()

    flash('Password changed successfully')
    return redirect(url_for('auth.signin'))

capstone_project/site/routes.py
from flask import Blueprint, render_template
from flask_login import login_user,logout_user, login_required,current_user
from capstone_project.models import User, db, QuizResult





site = Blueprint('site', __name__, template_folder='site_templates')


@site.route('/')
def home():
    return render_template("index.html")


@site.route('/profile')
@login_required
def profile():
    user = current_user
    first_name = user.first_name
    last_name = user.last_name
    quiz_results = QuizResult.query.filter_by(user_id=current_user.id).all()
    return render_template("profile.html", first_name=first_name, last_name=last_name, quiz_results=quiz_results)


@site.route('/tutor')
def tutor():
    return render_template('tutor.html')

capstone_project/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"
    />
    <link
      href="https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.css"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" />
    <link rel="stylesheet" href="../static/css/main.css">
    <title>Lady Bird</title>
    <script src="https://kit.fontawesome.com/yourcode.js" crossorigin="anonymous"></script>
  </head>
<body>
    <!--Nav Bar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light py-3 sticky-top">
      <div class="container">
        <a href="{{ url_for('site.home') }}" class="navbar-brand">
          <img src="../static/images/Logo1.png" max-width="100%" width="70%" alt="Logo">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navmenu">
          <span class="navbar-toggler-icon"></span>
        </button>
    
        <div class="collapse navbar-collapse" id="navmenu">
          <ul class="navbar-nav ms-auto">

            {% if current_user.is_authenticated %}
            <li class="nav-item">
              <a href="{{ url_for('site.profile') }}" class="nav-link text-dark">Profile</a>
            </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link text-dark" href="{{ url_for('auth.signup') }}">Sign Up</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-dark" href="{{ url_for('auth.signin') }}">Sign In</a>
            </li>
            <li class="nav-item">
              <a href="{{ url_for('site.tutor')}}" class="nav-link text-dark">Instructors</a>
            </li>
            {% if current_user.is_authenticated %}
            <li class="nav-item">
              <a href="{{ url_for('auth.logout') }}" class="nav-link text-dark">Logout</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
      <!-- Showcase -->
      
 <!--Create a space for content from other html pages-->
 {% block content %}
    
 {% endblock content %}
  







<!-- footer -->
<div class=" fixed-bottomcontainer my-5">
  <!-- Footer -->
  <footer
          class="text-center text-lg-start text-dark"
          style="background-color: #ECEFF1"
          >
    

    <!-- Section: Links  -->
    <section class="">
      <div class="container text-center text-md-start mt-5">
        <!-- Grid row -->
        <div class="row mt-3">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <!-- Content -->
            <h6 class="text-uppercase fw-bold">Lady Bird</h6>
            <hr
                class="mb-4 mt-0 d-inline-block mx-auto"
                style="width: 60px; background-color: #7c4dff; height: 2px"
                />
            <p>
              We focus on boarding the best and unique Tutors of all unique backgrounds to diversify your options to learn. 
               This is the space where Learning meets Fun!
            </p>
          </div>
          <!-- Grid column -->
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4  d-flex flex-column align-items-center justify-content-center" style="margin-top: -70px;">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold">Connect with Us!</h6>
            <hr
                class="mb-4 mt-0 d-inline-block mx-auto"
                style="width: 60px; background-color: #7c4dff; height: 2px"
                />
              <a href="#" class="me-4 text-reset"><i class="fab fa-facebook-f"></i></a>
              <a href="#" class="me-4 text-reset"><i class="fab fa-twitter"></i></a>
              <a href="#" class="me-4 text-reset"><i class="fab fa-linkedin"></i></a>
              <a href="#" class="me-4 text-reset"><i class="fab fa-instagram"></i></a>
              </div>
          
          <!-- Grid column -->
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold">Useful links</h6>
            <hr
                class="mb-4 mt-0 d-inline-block mx-auto"
                style="width: 60px; background-color: #7c4dff; height: 2px"
                />
            <p>
              <a href="#!" class="text-dark">Your Account</a>
            </p>
            <p>
              <a href="#!" class="text-dark">Become a Member</a>
            </p>
            <p>
              <a href="#!" class="text-dark">Tution Rates</a>
            </p>
            <p>
              <a href="#!" class="text-dark">Help</a>
            </p>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold">Contact</h6>
            <hr
                class="mb-4 mt-0 d-inline-block mx-auto"
                style="width: 60px; background-color: #7c4dff; height: 2px"
                />
            <p><i class="fas fa-home mr-3"></i> Austin, TX 78752, US</p>
            <p><i class="fas fa-envelope mr-3"></i> ladybird@gmail.com</p>
            <p><i class="fas fa-phone mr-3"></i> + 01 234 567 88</p>
            <p><i class="fas fa-print mr-3"></i> + 01 234 567 89</p>
          </div>
          <!-- Grid column -->
        </div>
        <!-- Grid row -->
      </div>
    </section>
    <!-- Section: Links  -->

  
  </footer>
  <!-- Footer -->
</div>
   

    
 









    <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
    crossorigin="anonymous"
  ></script>
  <script src="https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.js"></script>

  <script>
    mapboxgl.accessToken =
      'pk.eyJ1IjoiYnRyYXZlcnN5IiwiYSI6ImNrbmh0dXF1NzBtbnMyb3MzcTBpaG10eXcifQ.h5ZyYCglnMdOLAGGiL1Auw'
    var map = new mapboxgl.Map({
      container: 'map',
      style: 'mapbox://styles/mapbox/streets-v11',
      center: [-71.060982, 42.35725],
      zoom: 18,
    })
  </script>
</body>
</html>

capstone_project/templates/forms.html
<form method = "POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
        {{ form.email.label }}
        {{ form.email(style="width: 300px; border: 1px solid #ccc;", class="form-control", placeholder = "Place Email Here!") }}
    </fieldset>
    <br>
    <fieldset id="first-field">
    {{ form.first_name.label }}
    {{ form.first_name(style="width: 300px; border: 1px solid #ccc;", class="form-control", placeholder = "First Name")}}
    </fieldset>
    <br>
    <fieldset id="last-field">
{{ form.last_name.label }}
{{ form.last_name(style="width: 300px; border: 1px solid #ccc;", class="form-control", placeholder = "Last Name")}}
    </fieldset>
   <br>
    <fieldset id="pass-field">
    {{ form.password.label}}
    {{ form.password(style="width: 300px; border: 1px solid #ccc;", class="form-control", placeholder = "Password")}}
    </fieldset>
    <br>
    <fieldset id="pass-field">
        {{ form.password1.label}}
        {{ form.password1(style="width: 300px; border: 1px solid #ccc;", class="form-control", placeholder = "Confirm Password")}}
        <br>
        <br>
        </fieldset>
     {{ form.submit_button(style="width: 300px; border: 1px solid #ccc;", class = "btn btn-primary btn-block")}}
    </div>
</form>

capstone_project/templates/login_form.html
<form method = "POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(style="width: 300px; border: 1px solid #ccc;", class="form-control", placeholder = "Place Email Here!") }}
    </fieldset>
    <br>
    <fieldset id="pass-field">
        {{ form.password.label}}
        {{ form.password(style="width: 300px; border: 1px solid #ccc;", class="form-control", placeholder = "Password")}}
    </fieldset>
    <br>
    {{ form.submit_button(style="width: 300px; border: 1px solid #ccc;", class = "btn btn-primary btn-block")}}
    </div>
</form>